AI2202: Drop NEED_AIDL_NDK_PLATFORM_BACKEND
- LineageOS https://github.com/LineageOS/android_hardware_lineage_compat conflicts with this one.

Fixed:

error: hardware/interfaces/weaver/aidl/Android.bp:10:1: module "android.hardware.weaver-V1-ndk_platform" already defined
       hardware/lineage/compat/Android.bp:189:1 <-- previous definition here
04:13:06 soong bootstrap failed with: exit status 1

Signed-off-by: Jackeagle <jackeagle102@gmail.com>